### ISSUE TITLE
missing `#include <utility>`

### ISSUE THREAD

**Issue by martinus** [renzibei/fph-table#2]
I got a compile error in martinus/map_benchmark:

```cpp
/home/martinus/git/map_benchmark/external/fph__noseed_fph_map/include/fph/dynamic_fph_table.h:1509:33: error: no member named 'exchange' in namespace 'std'; did you mean '__exchange'?
                    seed1_(std::exchange(other.seed1_, 0x123456797291071ULL)),
                           ~~~~~^~~~~~~~
                                __exchange
```

It appears `#include <utility>` is missing: https://en.cppreference.com/w/cpp/utility/exchange, when I add the include it compiles

**Comment by renzibei** [comment]
Ok. I think it's related to compiler version. Let me update it.

**Comment by martinus** [comment]
probably, I'm using clang++ 13.0.1

**Comment by renzibei** [comment]
Fixed in the latest commit.

**Comment by renzibei** [comment]
> I got a compile error in martinus/map_benchmark:
> 
> ```c++
> /home/martinus/git/map_benchmark/external/fph__noseed_fph_map/include/fph/dynamic_fph_table.h:1509:33: error: no member named 'exchange' in namespace 'std'; did you mean '__exchange'?
>                     seed1_(std::exchange(other.seed1_, 0x123456797291071ULL)),
>                            ~~~~~^~~~~~~~
>                                 __exchange
> ```
> 
> It appears `#include <utility>` is missing: https://en.cppreference.com/w/cpp/utility/exchange, when I add the include it compiles

You can update the version of fph-table in your benchmark to 1a613abaefd42cb529f02b17ce5380ab78d841d3 or the latest version in the noseed branch.
