### ISSUE TITLE
Support no exceptions

### ISSUE THREAD

**Issue by alphanso** [renzibei/fph-table#3]
Hi,

I am developing production application which depend on this library. We have configuration where we enable and disable exceptions. I am able to compile with exceptions but without exception, compilation break. Please support  disabling exceptions as well.

Thanks for this library. It's really helpful. :)

**Comment by renzibei** [comment]
Hi, can you share how you disable the exceptions and what errors you encounter?

**Comment by alphanso** [comment]
I use following c++ flags:-
```
-O3 -fno-pie -fno-rtti -fno-exceptions
``` 
And I get following error
```
build/headers/fph/dynamic_fph_table.h:3124:78: error: exception handling disabled, use -fexceptions to enable
                     throw std::invalid_argument("c must be no less than 1.45");
```
I am getting this error with g++ 
```
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
```

**Comment by renzibei** [comment]
Hi, I have added support for -fno-exceptions in c9a0e52cb1e36d0bbbc015454a9a03cf13e26c11.

**Comment by alphanso** [comment]
Hi,
Thanks for quick update. I am getting following error :-
```
/opt/rh/gcc-toolset-11/root/usr/bin/ld: empty/CMakeFiles/empty.dir/empty/empty_strategy.cpp.o (symbol from plugin): in function `fph::dynamic::detail::ThrowInvalidArgument(char const*)':
(.text+0x0): multiple definition of `fph::dynamic::detail::ThrowInvalidArgument(char const*)'; empty/CMakeFiles/empty.dir/empty/main.cpp.o (symbol from plugin):(.text+0x0): first defined here
/opt/rh/gcc-toolset-11/root/usr/bin/ld: empty/CMakeFiles/empty.dir/empty/empty_strategy.cpp.o (symbol from plugin): in function `fph::dynamic::detail::ThrowInvalidArgument(char const*)':
```

**Comment by renzibei** [comment]
You can check the latest commit. Should be fixed.
