### ISSUE TITLE
fph::DynamicFphMap insert usage example

### ISSUE THREAD

**Issue by zsnjuts** [renzibei/fph-table#5]
There is no usage example for `insert(input_iterator, end_iterator)`. Can you supplement it? what type should input_iterator and end_iterator be? When I set them to iterator of `std:: vector<std:: pair<int, int>>`, there will be compile errors. Thanks in advance.

**Comment by renzibei** [comment]
@zsnjuts 

Hi, can you check whether the latest commit fixes your problem?

**Comment by renzibei** [comment]
@zsnjuts Sorry the last commit has a bug. I have pushed a new commit to fix it.

**Comment by zsnjuts** [comment]
Compile error solved, thanks!
And there is another question: If I want to build a `DynamicFphMap` or `MetaFphMap `from scratch and won't change it, what should I do? For example, I want to build a `DynamicFphMap<int, std::vector<int>>`, and my dataset is `std::vector<std::pair<int, std::vector<int>>>`, I should use `insert(input_iterator, output_iterator)` or `Build`? Which function is better? How should the template parameters of the `Build` be set? It seems that there is a lack of relevant content in the document. Thanks very much!

**Comment by renzibei** [comment]
When building from scratch, the map calls 'Build' to implement 'insert'. They are the same thing.

**Comment by zsnjuts** [comment]
The map will build fail when the data is large (the number of keys is 7,000,000). Is there any work around? By the way, the type of my key is int

**Comment by renzibei** [comment]
7 million should be fine for this map. Are there duplicated data? What's the key type? Is it possible that you provide the raw data to debug?

**Comment by zsnjuts** [comment]
There is no duplicated data, the key type is int64_t. Sorry, due to data confidentiality issues, I cannot provide the original data. The data characteristics are roughly: x, x+1, x+3, x+4, ..., x+m, y, y+2, y+3, ..., y+n. They are mainly concentrated in two data segments: [x, x+m], [y, y+n]. m << x, n << y, x+m << y. Therefore, the data distribution is very uneven and not a uniform distribution.

**Comment by renzibei** [comment]
I will try to reproduce the problem using the data distribution you provided. By the way, what's the ratio of m/n? What's the magnitude of x and y?
In the same time, can you try to insert the element one by one to see whether the problem remains?

**Comment by zsnjuts** [comment]
```
x = 1.6*10^15, x + m = 1.7*10^15
y = 7.16*10^18, y + n = 7.21*10^18
```
the ratio of element number of [x, x+m] and [y, y+n] is 1: 2

**Comment by renzibei** [comment]
May I know which hash table are you using? The seed one or the noseed one.
By the way, based on the data you provided, `m` is in the order of 10^14 and `n` is in the order of 5 * 10^16. Are you sure about this size?

**Comment by zsnjuts** [comment]
I tried both fph::DynamicFphMap (seed and noseed) and fph::MetaFphMap, even with strong seed generator. m and n is right. Although they are large, the element number of the two parts [x, x+m] and [y, y+n] is not that large (2.3 million and 4.6 million seperately)

**Comment by renzibei** [comment]
Can you verify whether the following test code has the same data distribution as your data?

```c++
#include "fph/dynamic_fph_table.h"
#include <unordered_set>
#include <cstdio>
#include <random>
int TestInsert() {

    constexpr int64_t X = 1'610'000'000'000'000LL, Y = 7'161'000'000'000'000'000LL;
    constexpr int64_t M = 100'000'000'000'000LL, N = 50'000'000'000'000'000LL;
    constexpr int64_t LEFT_COUNT = 2'300'000LL, RIGHT_COUNT = 4'600'000LL;
    int64_t cur_left_cnt = 0, cur_right_cnt = 0;
    auto rd = std::random_device{};
    auto gen = std::mt19937_64{rd()};
    auto left_dis = std::uniform_int_distribution<int64_t>{X, X + M};
    auto right_dis = std::uniform_int_distribution<int64_t>{Y, Y + N};
    std::unordered_set<int64_t> left_set, right_set;
    while (cur_left_cnt < LEFT_COUNT) {
        int64_t new_num = left_dis(gen);
        if (left_set.find(new_num) == left_set.end()) {
            left_set.insert(new_num);
            ++cur_left_cnt;
        }
    }
    while (cur_right_cnt < RIGHT_COUNT) {
        int64_t new_num = right_dis(gen);
        if (right_set.find(new_num) == right_set.end()) {
            right_set.insert(new_num);
            ++cur_right_cnt;
        }
    }
    std::vector<int64_t> src_vec{};
    src_vec.reserve(LEFT_COUNT + RIGHT_COUNT);
    for (auto &num: left_set) {
        src_vec.push_back(num);
    }
    for (auto &num: right_set) {
        src_vec.push_back(num);
    }
    auto test_fph_table = fph::dynamic_fph_set<int64_t>{};
    printf("Start to insert %zu elements\n", src_vec.size());
    test_fph_table.insert(src_vec.begin(), src_vec.end());
    printf("Insertion finished\n");
    for (auto num: src_vec) {
        if (test_fph_table.find(num) == test_fph_table.end()) {
            printf("Error, cannot find %lld in table\n", num);
            return -1;
        }
    }
    printf("Pass test\n");
    return 0;

}

int main() {
    TestInsert();
    return 0;
}
```

**Comment by zsnjuts** [comment]
They are almost identical. Whether these two parts are uniformly distributed still needs to be verified, but now it can be tested as uniform distribution.

**Comment by renzibei** [comment]
This test can pass easily. Can you adjust the parameters or test codes to make it fail?

**Comment by zsnjuts** [comment]
OK, I will try this test on my machine. How long did the build process take in your testing?

**Comment by zsnjuts** [comment]
The test passes easily on my machine and the build process is fast. I think their distribution is still different, I'll try to confirm the distribution, thanks!

**Comment by zsnjuts** [comment]
It turns out to be exist duplicate keys, and build will not fail after remove them, thanks for your time!
BTW, It would be even better if the document states that the keys required for `insert` and `Build` cannot be duplicated

**Comment by renzibei** [comment]
I'm considering to change the implementation of `insert` to make it consistent with `unordered_set`

**Comment by renzibei** [comment]
Implementation of `insert` has been changed now. It will be slower than `Build` when no duplicate keys exist though.
